
name: pdj-backoffice
services:
  pdj_backoffice:
    image:  ghcr.io/wiicode-projects/pdj-backoffice-dev:${IMAGE_TAG:-latest}
    container_name: pdj_backoffice
    networks:
      - proxy-network
    ports:
      - "127.0.0.1:83:80" # accessible uniquement en local
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:80/health"] #port 80 par défaut
      #test: ["CMD", "wget", "-qO-", "http://127.0.0.1:80/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
networks:
  proxy-network:
    external: true


