
name: pdj-backoffice
services:
  pdj_backoffice:
    image:  ghcr.io/wiicode-projects/pdj-backoffice-dev:latest
    container_name: pdj_backoffice
    ports:
      - ":80"
    networks:
      - proxy-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
networks:
  proxy-network:
    external: true
